//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.17020
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NxtManagerV3.Properties {
    
    /// <summary>
    /// Settings Class
    /// </summary>
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
	public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
		/// <summary>
		/// Default Instance
		/// </summary>
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
		/// <summary>
		/// ログファイルからNXT Stateを計算する
		/// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadNxtStateFromLogFile {
            get {
                return ((bool)(this["LoadNxtStateFromLogFile"]));
            }
        }
        
		/// <summary>
		/// NXT Stateのログをファイルに保存する
		/// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveNxtStateFile {
            get {
                return ((bool)(this["SaveNxtStateFile"]));
            }
        }
        
		/// <summary>
		/// NXT Stateの詳細をログに保存
		/// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveNxtStateDatail {
            get {
                return ((bool)(this["SaveNxtStateDatail"]));
            }
        }
    }
}
